version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-8s - %(name)s : %(message)s'
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  colored:
    class: colorlog.ColoredFormatter
    format: "%(asctime)s - %(log_color)s%(levelname)-8s%(reset)s - %(name)s : %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
    log_colors:
      DEBUG: "cyan"
      INFO: "green"
      WARNING: "yellow"
      ERROR: "red"
      CRITICAL: "bold_red,bg_white"
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: colored
    stream: ext://sys.stderr
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: mcp.log
    maxBytes: 10485760  # 10485760 = 1024*1024*10 = 10 MB
    backupCount: 2
    encoding: utf8
loggers:
  # self logger
  mcp_instana:
    level: DEBUG
    handlers: [stdout, file]
    propagate: False

  # FastMCP loggers
  fastmcp:
    level: INFO
    handlers: [stderr, file]
    propagate: False
  FastMCP:
    level: INFO
    handlers: [stderr, file]
    propagate: False
  mcp:
    level: INFO
    handlers: [stderr, file]
    propagate: False
  uvicorn:
    level: INFO
    handlers: [stderr, file]
    propagate: False
  uvicorn.error:
    level: INFO
    handlers: [stderr, file]
    propagate: False
  uvicorn.access:
    level: INFO
    handlers: [stderr, file]
    propagate: False
  sse_starlette:
    level: INFO
    handlers: [stderr, file]
    propagate: False

root:
  level: WARNING
  handlers: [stderr, file]
